// Source catalog for the dataset. tools/build-data.mjs turns this into data/movies.json and
// data/songs.json, adding Apple preview data from tools/cache/itunes.json.
//
// movies: [id, title, year, description]  (descriptions are original, premise only, no spoilers)
// songs:  [title, artist, movieId, alsoIn, scene, options?]
//   options.term   overrides the iTunes search term
//   options.trackId pins an Apple track when search only surfaces covers

export const movies = [
  // 1970s
  ['mean-streets-1973', 'Mean Streets', 1973, 'A small-time hustler in Little Italy tries to rise in the local mob while protecting his reckless, debt-ridden best friend.'],
  ['american-graffiti-1973', 'American Graffiti', 1973, 'On the last night of summer in 1962, a group of California teenagers cruise the strip, chase romance and weigh whether to leave town for college.'],
  ['live-and-let-die-1973', 'Live and Let Die', 1973, 'James Bond investigates the deaths of fellow agents and uncovers a Caribbean dictator\'s scheme to flood America with heroin.'],
  ['superfly-1972', 'Super Fly', 1972, 'A Harlem cocaine dealer plans one last big score so he can get out of the game for good.'],
  ['shaft-1971', 'Shaft', 1971, 'A cool private detective is hired by a Harlem crime boss to find his kidnapped daughter, pulling him between gangsters and the police.'],
  ['rocky-horror-picture-show-1975', 'The Rocky Horror Picture Show', 1975, 'A newly engaged couple with car trouble seeks help at a castle and finds a mad scientist hosting a very strange party.'],
  ['spy-who-loved-me-1977', 'The Spy Who Loved Me', 1977, 'James Bond teams up with a rival Soviet agent to find out who is stealing nuclear submarines.'],
  ['saturday-night-fever-1977', 'Saturday Night Fever', 1977, 'A Brooklyn paint-store clerk lives for weekends, when he is king of the local disco floor, and enters a dance contest with an ambitious new partner.'],
  ['smokey-and-the-bandit-1977', 'Smokey and the Bandit', 1977, 'A charming driver takes a bet to haul a truckload of beer across state lines in record time, with a furious sheriff on his tail.'],
  ['grease-1978', 'Grease', 1978, 'A greaser and a wholesome transfer student who shared a summer romance discover they now attend the same high school.'],
  ['thank-god-its-friday-1978', 'Thank God It\'s Friday', 1978, 'Over one Friday night at a Los Angeles disco, a crowd of regulars and newcomers chase love, a dance contest and a big break.'],
  ['life-of-brian-1979', 'Monty Python\'s Life of Brian', 1979, 'A man born in the stable next door to Jesus is mistaken for a messiah and can\'t shake his reluctant followers.'],
  ['muppet-movie-1979', 'The Muppet Movie', 1979, 'Kermit the Frog leaves his swamp for Hollywood, gathering friends on a cross-country road trip while a restaurateur pursues him.'],
  ['apocalypse-now-1979', 'Apocalypse Now', 1979, 'During the Vietnam War, an army captain travels upriver into Cambodia on a secret mission to find a colonel who has gone rogue.'],

  // 1980s
  ['caddyshack-1980', 'Caddyshack', 1980, 'At an exclusive golf club, a young caddie chases a scholarship while a brash developer, a snobbish judge and a gopher-obsessed groundskeeper collide.'],
  ['urban-cowboy-1980', 'Urban Cowboy', 1980, 'A country boy moves to Houston, finds his place at a honky-tonk with a mechanical bull, and falls into a stormy marriage.'],
  ['nine-to-five-1980', '9 to 5', 1980, 'Three office workers fed up with their sexist, lying boss accidentally take him hostage and start running the company better without him.'],
  ['blues-brothers-1980', 'The Blues Brothers', 1980, 'Two brothers on "a mission from God" reunite their old band to raise money for the orphanage where they grew up.'],
  ['officer-and-a-gentleman-1982', 'An Officer and a Gentleman', 1982, 'A tough loner enters navy flight school, clashes with a relentless drill instructor and falls for a local factory worker.'],
  ['fast-times-at-ridgemont-high-1982', 'Fast Times at Ridgemont High', 1982, 'A year in the life of Southern California high schoolers working mall jobs, navigating first romances and dodging a strict history teacher.'],
  ['rocky-iii-1982', 'Rocky III', 1982, 'Now a comfortable champion, Rocky Balboa is humbled by a hungry challenger and must rebuild his fighting spirit with an old rival\'s help.'],
  ['risky-business-1983', 'Risky Business', 1983, 'A straight-laced high schooler left home alone by his parents gets entangled with a call girl and a scheme that spirals out of control.'],
  ['flashdance-1983', 'Flashdance', 1983, 'A Pittsburgh welder who dances in a bar at night dreams of getting into a prestigious ballet school.'],
  ['outsiders-1983', 'The Outsiders', 1983, 'In 1960s Oklahoma, a teenage greaser and his friends are caught in a deadly feud with the wealthy kids across town.'],
  ['valley-girl-1983', 'Valley Girl', 1983, 'A popular San Fernando Valley teen falls for a punk from Hollywood, to the horror of her friends.'],
  ['big-chill-1983', 'The Big Chill', 1983, 'A group of college friends reunites for a weekend after a friend\'s funeral and takes stock of how their lives turned out.'],
  ['footloose-1984', 'Footloose', 1984, 'A city teen moves to a small town where dancing and rock music have been banned, and sets out to change the rules.'],
  ['ghostbusters-1984', 'Ghostbusters', 1984, 'Three out-of-work parapsychologists start a ghost-removal business in New York just as the city\'s supernatural activity spikes.'],
  ['karate-kid-1984', 'The Karate Kid', 1984, 'A bullied teenager new to Los Angeles learns karate, and life lessons, from his apartment building\'s quiet handyman.'],
  ['purple-rain-1984', 'Purple Rain', 1984, 'A gifted young Minneapolis musician struggles with a troubled home life, a rival band and a new romance.'],
  ['sixteen-candles-1984', 'Sixteen Candles', 1984, 'A high school sophomore\'s family forgets her sixteenth birthday amid her sister\'s wedding, while she pines for a senior who barely knows her.'],
  ['beverly-hills-cop-1984', 'Beverly Hills Cop', 1984, 'A wisecracking Detroit cop heads to Beverly Hills to investigate his friend\'s murder, much to the irritation of the local police.'],
  ['breakfast-club-1985', 'The Breakfast Club', 1985, 'Five students from different high school cliques spend a Saturday detention together and discover they have more in common than they thought.'],
  ['back-to-the-future-1985', 'Back to the Future', 1985, 'A teenager is accidentally sent back to 1955 in a time-traveling DeLorean and must make sure his parents still fall in love.'],
  ['goonies-1985', 'The Goonies', 1985, 'A group of kids facing the loss of their neighborhood find an old treasure map and set off after a legendary pirate\'s fortune.'],
  ['rocky-iv-1985', 'Rocky IV', 1985, 'Rocky Balboa travels to the Soviet Union to face a towering, scientifically trained boxer in a fight that becomes personal.'],
  ['pee-wees-big-adventure-1985', 'Pee-wee\'s Big Adventure', 1985, 'A childlike man-boy sets off on a cross-country journey to recover his beloved stolen bicycle.'],
  ['top-gun-1986', 'Top Gun', 1986, 'A hotshot naval aviator competes at an elite fighter-pilot school while dealing with a rivalry, a romance and the shadow of his father.'],
  ['ferris-buellers-day-off-1986', 'Ferris Bueller\'s Day Off', 1986, 'A charismatic high schooler fakes being sick to spend a perfect day in Chicago with his girlfriend and his anxious best friend.'],
  ['pretty-in-pink-1986', 'Pretty in Pink', 1986, 'A creative girl from the wrong side of the tracks is asked to prom by a rich classmate, testing her friendship with her devoted best friend.'],
  ['stand-by-me-1986', 'Stand by Me', 1986, 'In the summer of 1959, four boys from a small Oregon town hike into the woods to find the body of a missing kid.'],
  ['labyrinth-1986', 'Labyrinth', 1986, 'A teenage girl must solve a magical maze to rescue her baby brother from the Goblin King.'],
  ['highlander-1986', 'Highlander', 1986, 'An immortal Scottish swordsman, alive since the 1500s, faces the last of his kind in modern New York in a battle only one can survive.'],
  ['platoon-1986', 'Platoon', 1986, 'A young volunteer in Vietnam finds his platoon split between two sergeants with opposite moral codes.'],
  ['dirty-dancing-1987', 'Dirty Dancing', 1987, 'On a family vacation at a Catskills resort in 1963, a sheltered teenager falls for the resort\'s dance instructor.'],
  ['lost-boys-1987', 'The Lost Boys', 1987, 'Two brothers move to a California beach town and discover that the local gang of teenagers are vampires.'],
  ['mannequin-1987', 'Mannequin', 1987, 'A struggling artist working as a department-store window dresser falls for a mannequin who comes to life only when they are alone.'],
  ['good-morning-vietnam-1987', 'Good Morning, Vietnam', 1987, 'An irreverent DJ joins Armed Forces Radio in Saigon and wins over the troops while clashing with his superiors.'],
  ['beetlejuice-1988', 'Beetlejuice', 1988, 'A recently deceased couple haunting their own home hire an unhinged "bio-exorcist" to scare away the new family living there.'],
  ['cocktail-1988', 'Cocktail', 1988, 'An ambitious young bartender learns the flashy tricks of the trade from a cynical mentor and takes his act to Jamaica.'],
  ['beaches-1988', 'Beaches', 1988, 'Two women who met as children on the Atlantic City boardwalk sustain a lifelong friendship through very different lives.'],
  ['working-girl-1988', 'Working Girl', 1988, 'A secretary from Staten Island with big ideas poses as an executive when her scheming boss is laid up with a broken leg.'],
  ['say-anything-1989', 'Say Anything...', 1989, 'An underachieving kickboxing fan falls for the class valedictorian in the summer after high school.'],
  ['batman-1989', 'Batman', 1989, 'Gotham\'s mysterious vigilante faces a gangster transformed into a grinning, chaotic criminal mastermind.'],
  ['do-the-right-thing-1989', 'Do the Right Thing', 1989, 'On the hottest day of the year in a Brooklyn neighborhood, simmering racial tensions build around a local pizzeria.'],
  ['little-mermaid-1989', 'The Little Mermaid', 1989, 'A mermaid princess fascinated by the human world makes a risky deal with a sea witch to win the heart of a prince.'],

  // 1990s
  ['pretty-woman-1990', 'Pretty Woman', 1990, 'A wealthy businessman hires a Hollywood Boulevard escort to accompany him for a week, and neither expects to fall in love.'],
  ['ghost-1990', 'Ghost', 1990, 'After he is killed in a mugging, a man remains on earth as a ghost and enlists a reluctant psychic to protect the woman he loves.'],
  ['goodfellas-1990', 'Goodfellas', 1990, 'A young man from Brooklyn rises through the ranks of the mob over three decades, alongside two volatile associates.'],
  ['beauty-and-the-beast-1991', 'Beauty and the Beast', 1991, 'A bookish young woman becomes the prisoner of a cursed beast in his enchanted castle, where the household staff are living objects.'],
  ['wayne-s-world-1992', 'Wayne\'s World', 1992, 'Two metalhead friends who host a public-access TV show from a basement get a shot at the big time from a slick producer.'],
  ['reservoir-dogs-1992', 'Reservoir Dogs', 1992, 'After a jewelry heist goes wrong, the surviving criminals regroup at a warehouse and suspect one of them is a police informant.'],
  ['bodyguard-1992', 'The Bodyguard', 1992, 'A former Secret Service agent is hired to protect a pop superstar from a stalker, and their professional relationship becomes complicated.'],
  ['aladdin-1992', 'Aladdin', 1992, 'A street-smart young thief finds a magic lamp and a fast-talking genie, and uses his wishes to try to win a princess.'],
  ['mrs-doubtfire-1993', 'Mrs. Doubtfire', 1993, 'A divorced actor desperate to see his children disguises himself as an elderly Scottish nanny and gets hired by his ex-wife.'],
  ['dazed-and-confused-1993', 'Dazed and Confused', 1993, 'On the last day of school in 1976, Texas teenagers haze incoming freshmen, cruise around town and look for a party.'],
  ['philadelphia-1993', 'Philadelphia', 1993, 'A lawyer fired from his firm after his employers learn he has AIDS hires a homophobic attorney to sue for discrimination.'],
  ['reality-bites-1994', 'Reality Bites', 1994, 'A recent college graduate filming a documentary about her friends is torn between a slacker musician and a TV executive.'],
  ['forrest-gump-1994', 'Forrest Gump', 1994, 'A kind-hearted Alabama man with a low IQ stumbles through decades of American history while never forgetting his childhood love.'],
  ['pulp-fiction-1994', 'Pulp Fiction', 1994, 'The lives of two hitmen, a boxer, a gangster\'s wife and a pair of diner robbers intertwine across Los Angeles.'],
  ['lion-king-1994', 'The Lion King', 1994, 'A young lion prince flees his kingdom after his father\'s death and must one day return to face his scheming uncle.'],
  ['dangerous-minds-1995', 'Dangerous Minds', 1995, 'A former Marine becomes a teacher at an inner-city school and tries to reach a class of students everyone else has given up on.'],
  ['batman-forever-1995', 'Batman Forever', 1995, 'Batman faces Two-Face and the Riddler while a young acrobat seeks revenge for his family\'s murder.'],
  ['toy-story-1995', 'Toy Story', 1995, 'A pull-string cowboy doll feels threatened when a flashy space-ranger action figure becomes his owner\'s new favorite toy.'],
  ['trainspotting-1996', 'Trainspotting', 1996, 'A heroin addict in Edinburgh tries to get clean and break away from his chaotic, destructive group of friends.'],
  ['romeo-juliet-1996', 'Romeo + Juliet', 1996, 'Shakespeare\'s tragedy is staged in a modern beach city, where feuding families carry guns and the young lovers meet at a costume party.'],
  ['jerry-maguire-1996', 'Jerry Maguire', 1996, 'A sports agent who suddenly grows a conscience is fired and starts over with one client and one loyal accountant.'],
  ['titanic-1997', 'Titanic', 1997, 'A young aristocrat engaged to a wealthy man falls for a penniless artist aboard the ill-fated ocean liner.'],
  ['men-in-black-1997', 'Men in Black', 1997, 'A New York cop is recruited into a secret agency that polices the aliens living on Earth.'],
  ['boogie-nights-1997', 'Boogie Nights', 1997, 'A young dishwasher from the San Fernando Valley becomes a star in the adult film industry of the late 1970s.'],
  ['good-will-hunting-1997', 'Good Will Hunting', 1997, 'A janitor at MIT with a gift for mathematics works with a therapist to confront his past and decide his future.'],
  ['jackie-brown-1997', 'Jackie Brown', 1997, 'A flight attendant caught smuggling money for an arms dealer plays the dealer and the police against each other.'],
  ['full-monty-1997', 'The Full Monty', 1997, 'Unemployed steelworkers in Sheffield form an amateur striptease act to raise money.'],
  ['austin-powers-1997', 'Austin Powers: International Man of Mystery', 1997, 'A swinging 1960s British spy is thawed out in the 1990s to stop his old nemesis, who has also returned.'],
  ['big-lebowski-1998', 'The Big Lebowski', 1998, 'A laid-back bowler in Los Angeles is mistaken for a millionaire with the same name and drawn into a kidnapping scheme.'],
  ['armageddon-1998', 'Armageddon', 1998, 'NASA sends a crew of oil drillers into space to stop an asteroid on a collision course with Earth.'],
  ['city-of-angels-1998', 'City of Angels', 1998, 'An angel who watches over Los Angeles falls in love with a heart surgeon and considers giving up immortality for her.'],
  ['rushmore-1998', 'Rushmore', 1998, 'An eccentric prep-school student who runs every club on campus competes with a depressed industrialist for a teacher\'s affection.'],
  ['theres-something-about-mary-1998', 'There\'s Something About Mary', 1998, 'A man hires a private investigator to find his high school crush, only to learn several other men are pursuing her too.'],
  ['mulan-1998', 'Mulan', 1998, 'A young woman disguises herself as a man to take her ailing father\'s place in the Chinese army.'],
  ['notting-hill-1999', 'Notting Hill', 1999, 'A London travel bookshop owner\'s quiet life is upended when a famous American movie star walks into his store.'],
  ['shes-all-that-1999', 'She\'s All That', 1999, 'A popular high school senior bets he can turn an awkward art student into prom queen.'],
  ['10-things-i-hate-about-you-1999', '10 Things I Hate About You', 1999, 'A new student pays a brooding bad boy to date a sharp-tongued girl so he can date her younger sister.'],
  ['cruel-intentions-1999', 'Cruel Intentions', 1999, 'Two wealthy Manhattan step-siblings make a cruel wager over the seduction of the headmaster\'s virtuous daughter.'],
  ['fight-club-1999', 'Fight Club', 1999, 'An insomniac office worker and a charismatic soap salesman start an underground fighting club that grows into something much bigger.'],
  ['matrix-1999', 'The Matrix', 1999, 'A hacker learns from mysterious rebels that the world he knows is a simulation and that he may be the one to end it.'],
  ['office-space-1999', 'Office Space', 1999, 'Three fed-up software engineers plan revenge on their soul-crushing company after layoffs are announced.'],
  ['magnolia-1999', 'Magnolia', 1999, 'Over one day in the San Fernando Valley, the lives of a dying TV producer, a quiz-show host, a nurse and others intersect.'],
  ['tarzan-1999', 'Tarzan', 1999, 'A human baby raised by gorillas grows up in the jungle and is torn between two worlds when explorers arrive.'],

  // 2000s
  ['almost-famous-2000', 'Almost Famous', 2000, 'A teenage music journalist goes on tour with an up-and-coming rock band for Rolling Stone in the early 1970s.'],
  ['remember-the-titans-2000', 'Remember the Titans', 2000, 'A Black head coach takes over a newly integrated Virginia high school football team in 1971.'],
  ['o-brother-where-art-thou-2000', 'O Brother, Where Art Thou?', 2000, 'Three escaped convicts in 1930s Mississippi race to find hidden treasure, recording a hit record along the way.'],
  ['billy-elliot-2000', 'Billy Elliot', 2000, 'An eleven-year-old boy in a 1984 mining town secretly swaps boxing lessons for ballet.'],
  ['coyote-ugly-2000', 'Coyote Ugly', 2000, 'An aspiring songwriter moves to New York and takes a job at a rowdy bar where the bartenders dance on the counter.'],
  ['shrek-2001', 'Shrek', 2001, 'A grumpy ogre makes a deal with a tiny lord to rescue a princess from a dragon in exchange for getting his swamp back.'],
  ['moulin-rouge-2001', 'Moulin Rouge!', 2001, 'A young writer in 1899 Paris falls for the star courtesan of a famous nightclub, whose owner has promised her to a wealthy duke.'],
  ['bridget-joness-diary-2001', 'Bridget Jones\'s Diary', 2001, 'A thirty-something Londoner resolves to improve her life and finds herself between her charming boss and a stiff lawyer.'],
  ['royal-tenenbaums-2001', 'The Royal Tenenbaums', 2001, 'An estranged father tries to win back his family of former child prodigies by claiming he is dying.'],
  ['zoolander-2001', 'Zoolander', 2001, 'A dim-witted male supermodel is brainwashed by a fashion mogul to assassinate a world leader.'],
  ['donnie-darko-2001', 'Donnie Darko', 2001, 'A troubled teenager survives a freak accident and is visited by a giant rabbit who tells him the world will end in 28 days.'],
  ['8-mile-2002', '8 Mile', 2002, 'A young factory worker in Detroit tries to make his name as a rapper in the city\'s battle scene.'],
  ['lost-in-translation-2003', 'Lost in Translation', 2003, 'A fading movie star and a young woman, both adrift in a Tokyo hotel, form an unlikely bond.'],
  ['love-actually-2003', 'Love Actually', 2003, 'Interlinked stories follow a group of Londoners navigating love in the weeks before Christmas.'],
  ['kill-bill-vol-1-2003', 'Kill Bill: Vol. 1', 2003, 'A former assassin wakes from a coma and sets out for revenge on the team that attacked her on her wedding day.'],
  ['elf-2003', 'Elf', 2003, 'A human raised by Santa\'s elves at the North Pole travels to New York to find his real father.'],
  ['13-going-on-30-2004', '13 Going on 30', 2004, 'A thirteen-year-old girl wishes to be grown up and wakes up as a thirty-year-old magazine editor in Manhattan.'],
  ['napoleon-dynamite-2004', 'Napoleon Dynamite', 2004, 'An awkward Idaho teenager helps his new friend run for class president.'],
  ['garden-state-2004', 'Garden State', 2004, 'A struggling actor returns to New Jersey for his mother\'s funeral, stops taking his medication, and meets a free-spirited young woman.'],
  ['shrek-2-2004', 'Shrek 2', 2004, 'Shrek and Fiona visit her royal parents, who are not thrilled that their daughter married an ogre.'],
  ['anchorman-2004', 'Anchorman: The Legend of Ron Burgundy', 2004, 'A vain 1970s San Diego news anchor feels threatened when an ambitious female reporter joins his station.'],
  ['shaun-of-the-dead-2004', 'Shaun of the Dead', 2004, 'A London slacker tries to win back his girlfriend and save his mum during a zombie outbreak.'],
  ['eternal-sunshine-2004', 'Eternal Sunshine of the Spotless Mind', 2004, 'After a painful breakup, a man undergoes a procedure to erase his memories of his ex-girlfriend.'],
  ['wedding-crashers-2005', 'Wedding Crashers', 2005, 'Two divorce mediators who crash weddings to meet women fall for the daughters of a powerful politician.'],
  ['walk-the-line-2005', 'Walk the Line', 2005, 'The story of Johnny Cash\'s rise from an Arkansas cotton farm to music stardom, and his long romance with June Carter.'],
  ['little-miss-sunshine-2006', 'Little Miss Sunshine', 2006, 'A dysfunctional family drives a broken-down VW bus across the country so their young daughter can compete in a beauty pageant.'],
  ['marie-antoinette-2006', 'Marie Antoinette', 2006, 'A teenage Austrian archduchess is married off to the future king of France and navigates the excesses of Versailles.'],
  ['devil-wears-prada-2006', 'The Devil Wears Prada', 2006, 'An aspiring journalist lands a job as assistant to the demanding editor-in-chief of a top fashion magazine.'],
  ['cars-2006', 'Cars', 2006, 'A hotshot race car gets stranded in a forgotten Route 66 town on his way to the biggest race of his career.'],
  ['juno-2007', 'Juno', 2007, 'A witty sixteen-year-old with an unplanned pregnancy decides to find adoptive parents for the baby.'],
  ['once-2007', 'Once', 2007, 'A Dublin street musician and a Czech immigrant spend a week writing and recording songs together.'],
  ['mamma-mia-2008', 'Mamma Mia!', 2008, 'A bride-to-be on a Greek island secretly invites three men who might be her father to her wedding.'],
  ['slumdog-millionaire-2008', 'Slumdog Millionaire', 2008, 'A teenager from the slums of Mumbai is one question away from winning a game show and is accused of cheating.'],
  ['twilight-2008', 'Twilight', 2008, 'A teenage girl moves to a rainy Washington town and falls for a mysterious classmate who turns out to be a vampire.'],
  ['iron-man-2008', 'Iron Man', 2008, 'A billionaire weapons manufacturer is captured by insurgents and builds a powered suit of armor to escape.'],
  ['the-hangover-2009', 'The Hangover', 2009, 'Three groomsmen wake up in a trashed Las Vegas hotel suite with no memory of the night before and no sign of the groom.'],
  ['500-days-of-summer-2009', '(500) Days of Summer', 2009, 'A greeting-card writer revisits the ups and downs of his relationship with a coworker who doesn\'t believe in love.'],
  ['zombieland-2009', 'Zombieland', 2009, 'A nervous college student follows a strict set of survival rules as he travels a zombie-overrun America with three strangers.'],
  ['watchmen-2009', 'Watchmen', 2009, 'In an alternate 1985, a group of retired costumed heroes investigates the murder of one of their own.'],
  ['inglourious-basterds-2009', 'Inglourious Basterds', 2009, 'In Nazi-occupied France, a Jewish cinema owner and a squad of American soldiers each plot against the Nazi leadership.'],

  // 2010s
  ['easy-a-2010', 'Easy A', 2010, 'A clean-cut high schooler lets a lie about her love life spread, and her reputation takes on a life of its own.'],
  ['drive-2011', 'Drive', 2011, 'A quiet Hollywood stunt driver who moonlights as a getaway driver gets pulled into a heist to help his neighbor.'],
  ['bridesmaids-2011', 'Bridesmaids', 2011, 'A woman whose life is falling apart is named maid of honor for her best friend and competes with a polished rival bridesmaid.'],
  ['perks-of-being-a-wallflower-2012', 'The Perks of Being a Wallflower', 2012, 'A shy, troubled freshman is taken under the wing of two free-spirited seniors.'],
  ['pitch-perfect-2012', 'Pitch Perfect', 2012, 'A college freshman reluctantly joins an all-female a cappella group and helps shake up its old-fashioned style.'],
  ['skyfall-2012', 'Skyfall', 2012, 'After a mission goes wrong, James Bond\'s loyalty to M is tested as a former agent targets MI6.'],
  ['frozen-2013', 'Frozen', 2013, 'A fearless princess sets off to find her sister, whose icy powers have trapped their kingdom in eternal winter.'],
  ['despicable-me-2-2013', 'Despicable Me 2', 2013, 'A reformed supervillain is recruited by an anti-villain league to track down a new criminal mastermind.'],
  ['guardians-of-the-galaxy-2014', 'Guardians of the Galaxy', 2014, 'A human taken from Earth as a boy teams up with a band of misfit outlaws to protect a powerful orb.'],
  ['lego-movie-2014', 'The Lego Movie', 2014, 'An ordinary Lego construction worker is mistaken for the prophesied hero destined to save the universe.'],
  ['kingsman-2014', 'Kingsman: The Secret Service', 2014, 'A streetwise London teenager is recruited into a secret, gentlemanly spy organization.'],
  ['furious-7-2015', 'Furious 7', 2015, 'Dominic Toretto and his crew are hunted by the vengeful brother of a man they put in the hospital.'],
  ['spectre-2015', 'Spectre', 2015, 'A cryptic message from the past sends James Bond after a sinister organization.'],
  ['fifty-shades-of-grey-2015', 'Fifty Shades of Grey', 2015, 'A college student interviews a young billionaire and is drawn into an intense relationship on his terms.'],
  ['deadpool-2016', 'Deadpool', 2016, 'A wisecracking mercenary given healing powers by a rogue experiment hunts the man who disfigured him.'],
  ['moana-2016', 'Moana', 2016, 'A chief\'s daughter sails across the Pacific to find a demigod and restore the heart of an island goddess.'],
  ['trolls-2016', 'Trolls', 2016, 'An upbeat troll princess and a grumpy survivalist set out to rescue her friends from the creatures who eat trolls to feel happy.'],
  ['la-la-land-2016', 'La La Land', 2016, 'An aspiring actress and a jazz pianist fall in love in Los Angeles while pursuing their dreams.'],
  ['baby-driver-2017', 'Baby Driver', 2017, 'A young getaway driver who times every move to the music in his earbuds is coerced into one last heist.'],
  ['guardians-of-the-galaxy-vol-2-2017', 'Guardians of the Galaxy Vol. 2', 2017, 'The Guardians\' leader finally meets his father, a powerful being with secrets of his own.'],
  ['thor-ragnarok-2017', 'Thor: Ragnarok', 2017, 'Imprisoned on a garbage planet, Thor must win a gladiator contest and escape to stop the goddess of death from destroying Asgard.'],
  ['greatest-showman-2017', 'The Greatest Showman', 2017, 'A dreamer from humble beginnings builds a spectacular show around a troupe of unusual performers.'],
  ['coco-2017', 'Coco', 2017, 'A Mexican boy who dreams of being a musician despite his family\'s ban on music ends up in the Land of the Dead.'],
  ['black-panther-2018', 'Black Panther', 2018, 'The new king of the hidden, technologically advanced nation of Wakanda faces a challenger to the throne.'],
  ['a-star-is-born-2018', 'A Star Is Born', 2018, 'A hard-drinking country star discovers a talented singer-songwriter and helps launch her career as his own fades.'],
  ['spider-man-into-the-spider-verse-2018', 'Spider-Man: Into the Spider-Verse', 2018, 'Brooklyn teenager Miles Morales gains spider powers and meets Spider-People from other dimensions.'],
  ['captain-marvel-2019', 'Captain Marvel', 2019, 'An alien warrior with fragments of memories crash-lands in 1990s Los Angeles and uncovers her true past.'],
  ['joker-2019', 'Joker', 2019, 'A struggling party clown and aspiring comedian in Gotham City is pushed toward violence by a society that ignores him.'],

  // 2020s
  ['encanto-2021', 'Encanto', 2021, 'The only member of a magical Colombian family without a gift may be the one who can save the family\'s enchanted home.'],
  ['top-gun-maverick-2022', 'Top Gun: Maverick', 2022, 'Decades after flight school, a veteran naval aviator returns to train a group of young pilots for a dangerous mission.'],
  ['barbie-2023', 'Barbie', 2023, 'A doll living a perfect life in Barbieland starts having human worries and travels to the real world with Ken.'],
  ['saltburn-2023', 'Saltburn', 2023, 'An Oxford student is invited by a charismatic aristocratic classmate to spend the summer at his family\'s sprawling estate.'],
  ['deadpool-and-wolverine-2024', 'Deadpool & Wolverine', 2024, 'Deadpool recruits a reluctant variant of Wolverine to save his universe from erasure.'],
  ['wicked-2024', 'Wicked', 2024, 'At a school for sorcery in Oz, a green-skinned outcast and a popular blonde form an unlikely friendship.'],
  ['twisters-2024', 'Twisters', 2024, 'A storm-chasing scientist haunted by a past tornado teams up with a social-media storm chaser in Oklahoma.'],
  ['sinners-2025', 'Sinners', 2025, 'Twin brothers return to their Mississippi hometown in 1932 to open a juke joint, and the opening night draws something sinister.'],
  ['kpop-demon-hunters-2025', 'KPop Demon Hunters', 2025, 'A K-pop girl group secretly protects their fans from demons, and a rival boy band hides a dangerous secret.'],
];

export const songs = [
  // 1970s
  ['Jumpin\' Jack Flash', 'The Rolling Stones', 'mean-streets-1973', [], 'Plays as Johnny Boy makes his slow-motion entrance into Tony\'s bar.'],
  ['Be My Baby', 'The Ronettes', 'dirty-dancing-1987', ['mean-streets-1973'], 'Plays over the Dirty Dancing opening credits; also opens Mean Streets.'],
  ['Rock Around the Clock', 'Bill Haley & His Comets', 'american-graffiti-1973', [], 'Opens the film over the credits as the cars pull into Mel\'s Drive-In.'],
  ['Live and Let Die', 'Paul McCartney & Wings', 'live-and-let-die-1973', [], 'The film\'s title song, over the opening titles.'],
  ['Freddie\'s Dead', 'Curtis Mayfield', 'superfly-1972', [], 'Written for the film and heard as Freddie\'s story plays out.'],
  ['Theme from Shaft', 'Isaac Hayes', 'shaft-1971', [], 'Opens the film as Shaft walks through Times Square.'],
  ['Time Warp', 'Little Nell, Patricia Quinn & Richard O\'Brien', 'rocky-horror-picture-show-1975', [], 'Performed by the cast when Brad and Janet enter the castle.', { term: 'Time Warp Rocky Horror' }],
  ['Nobody Does It Better', 'Carly Simon', 'spy-who-loved-me-1977', [], 'The film\'s theme song, over the opening titles.'],
  ['Stayin\' Alive', 'Bee Gees', 'saturday-night-fever-1977', [], 'Opening credits as Tony struts down a Brooklyn street carrying a paint can.'],
  ['You Should Be Dancing', 'Bee Gees', 'saturday-night-fever-1977', [], 'Tony\'s solo dance on the lit-up 2001 Odyssey floor.'],
  ['Disco Inferno', 'The Trammps', 'saturday-night-fever-1977', ['reality-bites-1994'], 'Heard at the 2001 Odyssey disco.'],
  ['East Bound and Down', 'Jerry Reed', 'smokey-and-the-bandit-1977', [], 'Written for the film; plays as the Bandit starts the beer run. Jerry Reed also co-stars as Cledus.'],
  ['You\'re the One That I Want', 'John Travolta & Olivia Newton-John', 'grease-1978', ['deadpool-and-wolverine-2024'], 'Performed by Danny and Sandy at the carnival finale.'],
  ['Summer Nights', 'John Travolta & Olivia Newton-John', 'grease-1978', [], 'Danny and Sandy each tell their friends about their summer romance.'],
  ['Greased Lightnin\'', 'John Travolta', 'grease-1978', [], 'Danny and the T-Birds fantasize about fixing up Kenickie\'s car.'],
  ['Hopelessly Devoted to You', 'Olivia Newton-John', 'grease-1978', [], 'Sandy sings it alone in the backyard at night.'],
  ['Last Dance', 'Donna Summer', 'thank-god-its-friday-1978', [], 'Written for the film; Donna Summer performs it at the disco near the end.'],
  ['Always Look on the Bright Side of Life', 'Monty Python', 'life-of-brian-1979', [], 'Sung by Eric Idle\'s character in the final scene.', { trackId: 1443100831 }],
  ['Rainbow Connection', 'Kermit the Frog', 'muppet-movie-1979', [], 'Kermit sings it on a log in the swamp at the start of the film.'],
  ['The End', 'The Doors', 'apocalypse-now-1979', [], 'Opens the film over burning jungle and Willard in his Saigon hotel room.'],

  // 1980s
  ['I\'m Alright', 'Kenny Loggins', 'caddyshack-1980', [], 'Written for the film; plays over the opening and the gopher\'s dance.'],
  ['Lookin\' for Love', 'Johnny Lee', 'urban-cowboy-1980', [], 'Johnny Lee performs it at Gilley\'s honky-tonk.'],
  ['9 to 5', 'Dolly Parton', 'nine-to-five-1980', ['office-space-1999'], 'Dolly Parton\'s title song, over the opening credits.'],
  ['Everybody Needs Somebody to Love', 'The Blues Brothers', 'blues-brothers-1980', [], 'Jake and Elwood perform it at the big fundraising concert.'],
  ['Up Where We Belong', 'Joe Cocker & Jennifer Warnes', 'officer-and-a-gentleman-1982', [], 'Plays as Zack carries Paula out of the factory.'],
  ['Moving in Stereo', 'The Cars', 'fast-times-at-ridgemont-high-1982', [], 'Plays during Brad\'s poolside daydream about Linda.'],
  ['Somebody\'s Baby', 'Jackson Browne', 'fast-times-at-ridgemont-high-1982', [], 'Written for the film.'],
  ['Eye of the Tiger', 'Survivor', 'rocky-iii-1982', ['rocky-iv-1985'], 'Written for the film; opens it over Rocky\'s montage of title defenses.'],
  ['Old Time Rock and Roll', 'Bob Seger & The Silver Bullet Band', 'risky-business-1983', [], 'Joel slides across the floor in his socks and underwear.'],
  ['Flashdance... What a Feeling', 'Irene Cara', 'flashdance-1983', ['full-monty-1997'], 'Written for the film; plays over Alex\'s opening ride and during her audition.'],
  ['Maniac', 'Michael Sembello', 'flashdance-1983', [], 'Alex\'s training montage in her warehouse apartment.'],
  ['Stay Gold', 'Stevie Wonder', 'outsiders-1983', [], 'Written for the film and heard over the opening credits.'],
  ['I Melt with You', 'Modern English', 'valley-girl-1983', [], 'Plays during Randy and Julie\'s romantic montage and again at the end.'],
  ['I Heard It Through the Grapevine', 'Marvin Gaye', 'big-chill-1983', [], 'Opens the film as the friends hear the news.'],
  ['Ain\'t Too Proud to Beg', 'The Temptations', 'big-chill-1983', [], 'The friends dance while cleaning up the kitchen.'],
  ['Footloose', 'Kenny Loggins', 'footloose-1984', [], 'Opening credits over dancing feet, and the prom finale.'],
  ['Holding Out for a Hero', 'Bonnie Tyler', 'footloose-1984', ['shrek-2-2004'], 'Ren and Chuck\'s tractor game of chicken. A cover is sung in the Shrek 2 climax.'],
  ['Let\'s Hear It for the Boy', 'Deniece Williams', 'footloose-1984', [], 'Ren teaches Willard to dance.'],
  ['Ghostbusters', 'Ray Parker Jr.', 'ghostbusters-1984', ['zombieland-2009'], 'The title song, during the montage as the business takes off.'],
  ['You\'re the Best', 'Joe Esposito', 'karate-kid-1984', [], 'The tournament montage as Daniel advances.'],
  ['Cruel Summer', 'Bananarama', 'karate-kid-1984', [], 'Heard early in the film after Daniel moves to Reseda.'],
  ['When Doves Cry', 'Prince', 'purple-rain-1984', ['romeo-juliet-1996'], 'Plays over a montage of the Kid\'s life.'],
  ['Let\'s Go Crazy', 'Prince & The Revolution', 'purple-rain-1984', [], 'Opens the film at First Avenue.'],
  ['If You Were Here', 'Thompson Twins', 'sixteen-candles-1984', [], 'Plays in the final scene as Sam and Jake share a birthday cake.'],
  ['The Heat Is On', 'Glenn Frey', 'beverly-hills-cop-1984', [], 'Written for the film.'],
  ['Neutron Dance', 'The Pointer Sisters', 'beverly-hills-cop-1984', [], 'Plays during the opening truck chase through Detroit.'],
  ['Don\'t You (Forget About Me)', 'Simple Minds', 'breakfast-club-1985', ['pitch-perfect-2012', 'easy-a-2010'], 'Written for the film; opens and closes it as Bender raises his fist. Pitch Perfect\'s Beca watches that ending.'],
  ['The Power of Love', 'Huey Lewis & The News', 'back-to-the-future-1985', ['deadpool-and-wolverine-2024'], 'Marty skateboards to school through Hill Valley.'],
  ['Johnny B. Goode', 'Chuck Berry', 'back-to-the-future-1985', ['american-graffiti-1973'], 'Marty plays it at the Enchantment Under the Sea dance.'],
  ['Mr. Sandman', 'The Four Aces', 'back-to-the-future-1985', [], 'Plays as Marty walks into 1955 Hill Valley.', { trackId: 1444153671 }],
  ['Earth Angel', 'The Penguins', 'back-to-the-future-1985', [], 'The slow dance at the Enchantment Under the Sea dance.'],
  ['The Goonies \'R\' Good Enough', 'Cyndi Lauper', 'goonies-1985', [], 'Written for the film.'],
  ['Burning Heart', 'Survivor', 'rocky-iv-1985', [], 'Written for the film; part of Rocky\'s montage sequences.'],
  ['Living in America', 'James Brown', 'rocky-iv-1985', [], 'James Brown performs it before the Apollo Creed vs. Drago exhibition.'],
  ['No Easy Way Out', 'Robert Tepper', 'rocky-iv-1985', [], 'Rocky\'s night-drive montage.'],
  ['Tequila', 'The Champs', 'pee-wees-big-adventure-1985', ['baby-driver-2017'], 'Pee-wee dances on the bar to win over a biker gang.'],
  ['Danger Zone', 'Kenny Loggins', 'top-gun-1986', ['top-gun-maverick-2022'], 'Opens the film over carrier launches; reprised at the start of Top Gun: Maverick.'],
  ['Take My Breath Away', 'Berlin', 'top-gun-1986', [], 'Written for the film; Maverick and Charlie\'s love scene.'],
  ['Great Balls of Fire', 'Jerry Lee Lewis', 'top-gun-1986', ['top-gun-maverick-2022', 'stand-by-me-1986'], 'Goose plays it on the bar piano; Rooster plays it in Top Gun: Maverick.'],
  ['You\'ve Lost That Lovin\' Feelin\'', 'The Righteous Brothers', 'top-gun-1986', [], 'Maverick and Goose serenade Charlie at the bar.', { trackId: 1428758750 }],
  ['Twist and Shout', 'The Beatles', 'ferris-buellers-day-off-1986', [], 'Ferris lip-syncs on a float in the Chicago parade.'],
  ['Oh Yeah', 'Yello', 'ferris-buellers-day-off-1986', [], 'Plays whenever Cameron\'s father\'s Ferrari is on screen.'],
  ['Danke Schoen', 'Wayne Newton', 'ferris-buellers-day-off-1986', [], 'Ferris sings it in the shower and later on the parade float.'],
  ['If You Leave', 'Orchestral Manoeuvres in the Dark', 'pretty-in-pink-1986', [], 'Written for the film; plays at the prom finale.', { trackId: 1440839073 }],
  ['Try a Little Tenderness', 'Otis Redding', 'pretty-in-pink-1986', [], 'Duckie lip-syncs and dances to it in the record store.'],
  ['Stand by Me', 'Ben E. King', 'stand-by-me-1986', ['urban-cowboy-1980'], 'The title song, over the closing scene and credits.'],
  ['Magic Dance', 'David Bowie', 'labyrinth-1986', [], 'Jareth sings it with his goblins after taking the baby.'],
  ['Who Wants to Live Forever', 'Queen', 'highlander-1986', [], 'Written for the film; plays as Connor watches his wife grow old.'],
  ['The Tracks of My Tears', 'Smokey Robinson & The Miracles', 'platoon-1986', ['big-chill-1983'], 'Heard in the soldiers\' underground hangout. Also on The Big Chill soundtrack.'],
  ['(I\'ve Had) The Time of My Life', 'Bill Medley & Jennifer Warnes', 'dirty-dancing-1987', [], 'Written for the film; the final dance and the lift.'],
  ['Hungry Eyes', 'Eric Carmen', 'dirty-dancing-1987', [], 'Johnny and Baby\'s dance-practice montage.'],
  ['She\'s Like the Wind', 'Patrick Swayze', 'dirty-dancing-1987', [], 'Sung by the film\'s star, Patrick Swayze.'],
  ['Do You Love Me', 'The Contours', 'dirty-dancing-1987', [], 'The staff dance party in the cabins.'],
  ['Cry Little Sister', 'Gerard McMann', 'lost-boys-1987', [], 'Written for the film; plays as the brothers arrive in Santa Carla.'],
  ['Nothing\'s Gonna Stop Us Now', 'Starship', 'mannequin-1987', [], 'Written for the film; Jonathan and Emmy\'s montage.'],
  ['What a Wonderful World', 'Louis Armstrong', 'good-morning-vietnam-1987', [], 'Plays over a montage of everyday life and violence in Vietnam.'],
  ['Day-O (The Banana Boat Song)', 'Harry Belafonte', 'beetlejuice-1988', [], 'The possessed dinner guests are forced to lip-sync and dance.'],
  ['Jump in the Line (Shake, Senora)', 'Harry Belafonte', 'beetlejuice-1988', [], 'Lydia floats and dances in the final scene.'],
  ['Kokomo', 'The Beach Boys', 'cocktail-1988', [], 'Written for the film; plays as Brian tends bar in Jamaica.'],
  ['Don\'t Worry, Be Happy', 'Bobby McFerrin', 'cocktail-1988', [], 'Plays in Jamaica as Brian enjoys beach life.'],
  ['Wind Beneath My Wings', 'Bette Midler', 'beaches-1988', [], 'Sung by CC near the end of the film.'],
  ['Let the River Run', 'Carly Simon', 'working-girl-1988', [], 'Written for the film; Tess rides the Staten Island Ferry over the opening.'],
  ['In Your Eyes', 'Peter Gabriel', 'say-anything-1989', [], 'Lloyd holds a boombox over his head outside Diane\'s window.'],
  ['Partyman', 'Prince', 'batman-1989', [], 'The Joker and his gang deface the art museum.'],
  ['Fight the Power', 'Public Enemy', 'do-the-right-thing-1989', [], 'Opens the film as Rosie Perez dances, and blasts from Radio Raheem\'s boombox.', { trackId: 1440838444 }],
  ['Under the Sea', 'Samuel E. Wright', 'little-mermaid-1989', [], 'Sebastian tries to convince Ariel to stay in the ocean.'],
  ['Part of Your World', 'Jodi Benson', 'little-mermaid-1989', [], 'Ariel sings in her grotto full of human treasures.'],
  ['Kiss the Girl', 'Samuel E. Wright', 'little-mermaid-1989', [], 'Sebastian sets the mood during the lagoon boat ride.'],

  // 1990s
  ['It Must Have Been Love', 'Roxette', 'pretty-woman-1990', [], 'Plays as Vivian prepares to leave the hotel.'],
  ['Oh, Pretty Woman', 'Roy Orbison', 'pretty-woman-1990', [], 'The Rodeo Drive shopping spree.'],
  ['King of Wishful Thinking', 'Go West', 'pretty-woman-1990', [], 'Written for the film; plays during Vivian and Edward\'s week together.'],
  ['Unchained Melody', 'The Righteous Brothers', 'ghost-1990', [], 'The pottery wheel scene.'],
  ['Layla', 'Derek & The Dominos', 'goodfellas-1990', [], 'The piano coda plays over the discovery of bodies after the Lufthansa heist.'],
  ['Then He Kissed Me', 'The Crystals', 'goodfellas-1990', [], 'Henry leads Karen through the Copacabana kitchen in one long shot.'],
  ['Jump into the Fire', 'Harry Nilsson', 'goodfellas-1990', [], 'Henry\'s paranoid, helicopter-haunted final day.'],
  ['Rags to Riches', 'Tony Bennett', 'goodfellas-1990', [], 'Opens the film after "As far back as I can remember".'],
  ['Be Our Guest', 'Jerry Orbach & Angela Lansbury', 'beauty-and-the-beast-1991', [], 'Lumiere and the castle staff throw Belle a dinner show.'],
  ['Gaston', 'Richard White & Jesse Corti', 'beauty-and-the-beast-1991', [], 'LeFou cheers up Gaston in the tavern.'],
  ['Bohemian Rhapsody', 'Queen', 'wayne-s-world-1992', [], 'Wayne and friends headbang in the AMC Pacer.'],
  ['Dream Weaver', 'Gary Wright', 'wayne-s-world-1992', [], 'Plays when Wayne first sees Cassandra.'],
  ['Stuck in the Middle with You', 'Stealers Wheel', 'reservoir-dogs-1992', [], 'Mr. Blonde dances in the warehouse during the infamous torture scene.'],
  ['Little Green Bag', 'George Baker Selection', 'reservoir-dogs-1992', [], 'The opening-credits slow-motion walk.'],
  ['Hooked on a Feeling', 'Blue Swede', 'guardians-of-the-galaxy-2014', ['reservoir-dogs-1992'], 'Quill\'s Walkman plays it in the Kyln prison; also heard on K-Billy radio in Reservoir Dogs.'],
  ['I Will Always Love You', 'Whitney Houston', 'bodyguard-1992', [], 'Rachel sings it at the end of the film.'],
  ['I\'m Every Woman', 'Whitney Houston', 'bodyguard-1992', [], 'Rachel performs it.'],
  ['A Whole New World', 'Brad Kane & Lea Salonga', 'aladdin-1992', [], 'Aladdin and Jasmine\'s magic carpet ride.'],
  ['Friend Like Me', 'Robin Williams', 'aladdin-1992', [], 'The Genie introduces himself and his powers.'],
  ['Prince Ali', 'Robin Williams', 'aladdin-1992', [], 'The Genie leads Aladdin\'s grand parade into Agrabah.'],
  ['Dude (Looks Like a Lady)', 'Aerosmith', 'mrs-doubtfire-1993', [], 'Mrs. Doubtfire dances with the vacuum cleaner.'],
  ['Sweet Emotion', 'Aerosmith', 'dazed-and-confused-1993', [], 'Opens the film as a GTO cruises into the school parking lot.'],
  ['School\'s Out', 'Alice Cooper', 'dazed-and-confused-1993', [], 'The last bell of the school year.'],
  ['Slow Ride', 'Foghat', 'dazed-and-confused-1993', ['top-gun-maverick-2022'], 'Heard in the film.'],
  ['Streets of Philadelphia', 'Bruce Springsteen', 'philadelphia-1993', [], 'Written for the film; opens it over scenes of the city.'],
  ['My Sharona', 'The Knack', 'reality-bites-1994', [], 'The friends dance in a gas station convenience store.'],
  ['Stay (I Missed You)', 'Lisa Loeb', 'reality-bites-1994', [], 'Plays over the end of the film.'],
  ['Fortunate Son', 'Creedence Clearwater Revival', 'forrest-gump-1994', [], 'Forrest arrives in Vietnam by helicopter.'],
  ['Running on Empty', 'Jackson Browne', 'forrest-gump-1994', [], 'Forrest\'s cross-country running montage.'],
  ['Sweet Home Alabama', 'Lynyrd Skynyrd', 'forrest-gump-1994', ['8-mile-2002'], 'Heard during Jenny\'s years away from Forrest.'],
  ['Hound Dog', 'Elvis Presley', 'forrest-gump-1994', [], 'Young Forrest\'s leg-brace dance inspires a young guitarist.'],
  ['Free Bird', 'Lynyrd Skynyrd', 'kingsman-2014', ['forrest-gump-1994'], 'Galahad\'s church brawl; also heard in Forrest Gump.'],
  ['Misirlou', 'Dick Dale & His Del-Tones', 'pulp-fiction-1994', [], 'Kicks in after the diner robbery opening, over the credits.'],
  ['You Never Can Tell', 'Chuck Berry', 'pulp-fiction-1994', [], 'Vincent and Mia\'s twist contest at Jack Rabbit Slim\'s.'],
  ['Son of a Preacher Man', 'Dusty Springfield', 'pulp-fiction-1994', [], 'Plays as Vincent arrives at Marsellus\'s house to pick up Mia.'],
  ['Girl, You\'ll Be a Woman Soon', 'Urge Overkill', 'pulp-fiction-1994', [], 'Mia dances alone in the house.'],
  ['Jungle Boogie', 'Kool & The Gang', 'pulp-fiction-1994', [], 'The opening credits cut from Misirlou to it, as if changing radio stations.'],
  ['Circle of Life', 'Carmen Twillie & Lebo M.', 'lion-king-1994', [], 'Opens the film at Pride Rock as Simba is presented.'],
  ['Hakuna Matata', 'Nathan Lane, Ernie Sabella, Jason Weaver & Joseph Williams', 'lion-king-1994', [], 'Timon and Pumbaa teach Simba their carefree philosophy.'],
  ['Can You Feel the Love Tonight', 'Joseph Williams, Sally Dworsky, Nathan Lane, Ernie Sabella & Kristle Edwards', 'lion-king-1994', [], 'Simba and Nala reunite in the jungle.', { term: 'Can You Feel the Love Tonight Lion King Sally Dworsky' }],
  ['Gangsta\'s Paradise', 'Coolio', 'dangerous-minds-1995', [], 'Written for the film; opens it over the school neighborhood.'],
  ['Kiss from a Rose', 'Seal', 'batman-forever-1995', [], 'Featured in the film and over the end credits.'],
  ['You\'ve Got a Friend in Me', 'Randy Newman', 'toy-story-1995', [], 'Opens the film as Andy plays with Woody.'],
  ['Lust for Life', 'Iggy Pop', 'trainspotting-1996', [], 'Renton and Spud run from security down Princes Street.'],
  ['Born Slippy .NUXX', 'Underworld', 'trainspotting-1996', [], 'Plays over the final scene as Renton walks away with the bag.'],
  ['Perfect Day', 'Lou Reed', 'trainspotting-1996', [], 'Renton\'s overdose, sinking into the carpet.'],
  ['Kissing You', 'Des\'ree', 'romeo-juliet-1996', [], 'Des\'ree performs it at the party as Romeo and Juliet meet through a fish tank.', { trackId: 211424924 }],
  ['Lovefool', 'The Cardigans', 'romeo-juliet-1996', ['cruel-intentions-1999'], 'Heard in the film.'],
  ['Free Fallin\'', 'Tom Petty', 'jerry-maguire-1996', [], 'Jerry sings along in the car after signing Rod.'],
  ['Secret Garden', 'Bruce Springsteen', 'jerry-maguire-1996', [], 'Plays during Jerry and Dorothy\'s romance.'],
  ['My Heart Will Go On', 'Céline Dion', 'titanic-1997', [], 'Written for the film; plays over the end credits after its melody runs through the score.'],
  ['Men in Black', 'Will Smith', 'men-in-black-1997', [], 'The title song over the end credits.'],
  ['Sister Christian', 'Night Ranger', 'boogie-nights-1997', [], 'The tense drug-deal scene at Rahad Jackson\'s house.'],
  ['Miss Misery', 'Elliott Smith', 'good-will-hunting-1997', [], 'Written for the film; plays at the end.'],
  ['Across 110th Street', 'Bobby Womack', 'jackie-brown-1997', [], 'Opens the film as Jackie glides through LAX.'],
  ['You Sexy Thing', 'Hot Chocolate', 'full-monty-1997', ['boogie-nights-1997'], 'The men\'s final striptease performance.'],
  ['Soul Bossa Nova', 'Quincy Jones', 'austin-powers-1997', [], 'Austin\'s opening dance through swinging London.'],
  ['The Man in Me', 'Bob Dylan', 'big-lebowski-1998', [], 'The Dude\'s floating dream sequence after being knocked out.'],
  ['Just Dropped In (To See What Condition My Condition Was In)', 'Kenny Rogers & The First Edition', 'big-lebowski-1998', [], 'The "Gutterballs" dream sequence.'],
  ['Lookin\' Out My Back Door', 'Creedence Clearwater Revival', 'big-lebowski-1998', [], 'The Dude listens to Creedence in his car.'],
  ['I Don\'t Want to Miss a Thing', 'Aerosmith', 'armageddon-1998', [], 'Written for the film; plays as Harry says goodbye.'],
  ['Iris', 'Goo Goo Dolls', 'city-of-angels-1998', ['deadpool-and-wolverine-2024'], 'Written for the film.'],
  ['Ooh La La', 'Faces', 'rushmore-1998', [], 'Plays over the final dance scene.'],
  ['Making Time', 'The Creation', 'rushmore-1998', [], 'Max\'s montage of extracurricular activities.'],
  ['Build Me Up Buttercup', 'The Foundations', 'theres-something-about-mary-1998', [], 'The cast sings along over the end credits.'],
  ['I\'ll Make a Man Out of You', 'Donny Osmond', 'mulan-1998', [], 'Shang trains the new recruits.', { trackId: 1440662805 }],
  ['She', 'Elvis Costello', 'notting-hill-1999', [], 'Plays over the closing montage.'],
  ['Ain\'t No Sunshine', 'Bill Withers', 'notting-hill-1999', [], 'William walks through a year of seasons on Portobello Road.'],
  ['Kiss Me', 'Sixpence None the Richer', 'shes-all-that-1999', [], 'Laney descends the stairs after her makeover.'],
  ['Can\'t Take My Eyes Off You', 'Frankie Valli', '10-things-i-hate-about-you-1999', [], 'Patrick serenades Kat from the stadium bleachers.'],
  ['Bitter Sweet Symphony', 'The Verve', 'cruel-intentions-1999', [], 'Annette drives off in the final scene.'],
  ['Where Is My Mind?', 'Pixies', 'fight-club-1999', [], 'Plays over the final scene as the skyline changes.'],
  ['Wake Up', 'Rage Against the Machine', 'matrix-1999', [], 'Plays as Neo flies off at the end.'],
  ['Damn It Feels Good to Be a Gangsta', 'Geto Boys', 'office-space-1999', [], 'The three friends smash the printer in a field.'],
  ['Wise Up', 'Aimee Mann', 'magnolia-1999', [], 'The characters each sing along in turn.'],
  ['You\'ll Be in My Heart', 'Phil Collins', 'tarzan-1999', [], 'Kala comforts the infant Tarzan.'],

  // 2000s
  ['Tiny Dancer', 'Elton John', 'almost-famous-2000', [], 'The band and crew sing along on the tour bus.'],
  ['Ain\'t No Mountain High Enough', 'Marvin Gaye & Tammi Terrell', 'guardians-of-the-galaxy-2014', ['remember-the-titans-2000'], 'Plays in the final scene as Quill opens his mother\'s gift; the Titans sing it in the locker room.'],
  ['Na Na Hey Hey Kiss Him Goodbye', 'Steam', 'remember-the-titans-2000', [], 'The crowd sings it as the Titans close out games.', { trackId: 1434901987 }],
  ['I Am a Man of Constant Sorrow', 'The Soggy Bottom Boys', 'o-brother-where-art-thou-2000', [], 'The escaped convicts record it at a radio station.'],
  ['Town Called Malice', 'The Jam', 'billy-elliot-2000', ['valley-girl-1983'], 'Billy dances through the streets in frustration.'],
  ['I Love to Boogie', 'T. Rex', 'billy-elliot-2000', [], 'Heard as Billy dances early in the film.'],
  ['Can\'t Fight the Moonlight', 'LeAnn Rimes', 'coyote-ugly-2000', [], 'Written for the film; Violet\'s showcase at the end.'],
  ['All Star', 'Smash Mouth', 'shrek-2001', [], 'Opens the film as Shrek goes about his morning.'],
  ['I\'m a Believer', 'Smash Mouth', 'shrek-2001', [], 'The cast parties at the wedding finale.'],
  ['Lady Marmalade', 'Christina Aguilera, Lil\' Kim, Mya & P!nk', 'moulin-rouge-2001', [], 'Recorded for the film; the opening number at the club.'],
  ['Out of Reach', 'Gabrielle', 'bridget-joness-diary-2001', [], 'Written for the film; Bridget\'s lonely Christmas.'],
  ['These Days', 'Nico', 'royal-tenenbaums-2001', [], 'Margot steps off the Green Line bus in slow motion.'],
  ['Needle in the Hay', 'Elliott Smith', 'royal-tenenbaums-2001', [], 'Richie\'s darkest moment in the bathroom.'],
  ['Wake Me Up Before You Go-Go', 'Wham!', 'zoolander-2001', [], 'The male models\' gasoline fight at the gas station.'],
  ['Mad World', 'Gary Jules & Michael Andrews', 'donnie-darko-2001', [], 'Recorded for the film; plays over the closing montage.'],
  ['Head Over Heels', 'Tears for Fears', 'donnie-darko-2001', [], 'The slow-motion tour of Middlesex Ridge School.'],
  ['The Killing Moon', 'Echo & The Bunnymen', 'donnie-darko-2001', [], 'Opens the film as Donnie bikes home.'],
  ['Lose Yourself', 'Eminem', '8-mile-2002', [], 'Written for the film; plays over the closing walk.'],
  ['Just Like Honey', 'The Jesus and Mary Chain', 'lost-in-translation-2003', [], 'Plays in the final scene after the whispered goodbye.'],
  ['Jump (For My Love)', 'The Pointer Sisters', 'love-actually-2003', [], 'The Prime Minister dances alone through 10 Downing Street.'],
  ['Christmas Is All Around', 'Billy Mack (Bill Nighy)', 'love-actually-2003', [], 'Billy Mack\'s comeback Christmas single.', { term: 'Christmas Is All Around Bill Nighy', trackId: 290788911 }],
  ['Bang Bang (My Baby Shot Me Down)', 'Nancy Sinatra', 'kill-bill-vol-1-2003', [], 'Plays over the opening credits.'],
  ['Woo Hoo', 'The 5.6.7.8\'s', 'kill-bill-vol-1-2003', [], 'The band performs it at the House of Blue Leaves.', { trackId: 497871431 }],
  ['Battle Without Honor or Humanity', 'Tomoyasu Hotei', 'kill-bill-vol-1-2003', [], 'The Crazy 88 arrive with O-Ren at the House of Blue Leaves.'],
  ['Baby, It\'s Cold Outside', 'Zooey Deschanel & Leon Redbone', 'elf-2003', [], 'Jovie sings in the shower as Buddy joins in.'],
  ['Thriller', 'Michael Jackson', '13-going-on-30-2004', [], 'Jenna gets the party dancing.'],
  ['Canned Heat', 'Jamiroquai', 'napoleon-dynamite-2004', [], 'Napoleon\'s dance at the school assembly.'],
  ['New Slang', 'The Shins', 'garden-state-2004', [], 'Sam tells Andrew this song will change his life.'],
  ['Let Go', 'Frou Frou', 'garden-state-2004', [], 'Plays in the final scene.'],
  ['Accidentally in Love', 'Counting Crows', 'shrek-2-2004', [], 'Written for the film; the honeymoon montage.'],
  ['Afternoon Delight', 'Starland Vocal Band', 'anchorman-2004', ['boogie-nights-1997', 'good-will-hunting-1997'], 'The news team sings it a cappella.'],
  ['Don\'t Stop Me Now', 'Queen', 'shaun-of-the-dead-2004', [], 'The jukebox plays as they beat a zombie with pool cues.'],
  ['Everybody\'s Gotta Learn Sometime', 'Beck', 'eternal-sunshine-2004', [], 'Recorded for the film; plays as Joel\'s memories fade.'],
  ['Shout', 'The Isley Brothers', 'wedding-crashers-2005', ['10-things-i-hate-about-you-1999'], 'Plays over the opening wedding-crashing montage.'],
  ['Jackson', 'Joaquin Phoenix & Reese Witherspoon', 'walk-the-line-2005', [], 'Johnny and June perform it on stage.'],
  ['Super Freak', 'Rick James', 'little-miss-sunshine-2006', [], 'Olive\'s talent-show routine.'],
  ['I Want Candy', 'Bow Wow Wow', 'marie-antoinette-2006', ['napoleon-dynamite-2004'], 'Marie and her friends\' lavish shopping montage.'],
  ['Suddenly I See', 'KT Tunstall', 'devil-wears-prada-2006', [], 'Opens the film as Andy and others get ready for work.'],
  ['Life Is a Highway', 'Rascal Flatts', 'cars-2006', [], 'Lightning McQueen rides to California in Mack.'],
  ['Real Gone', 'Sheryl Crow', 'cars-2006', [], 'Opens the film at the race.'],
  ['Anyone Else But You', 'The Moldy Peaches', 'juno-2007', [], 'Juno and Paulie sing it in the final scene.'],
  ['Falling Slowly', 'Glen Hansard & Markéta Irglová', 'once-2007', [], 'The two leads play it together in a music shop.'],
  ['Dancing Queen', 'Meryl Streep, Julie Walters & Christine Baranski', 'mamma-mia-2008', [], 'Donna and her friends lead the island women in song.', { term: 'Dancing Queen Mamma Mia Meryl Streep' }],
  ['Lay All Your Love on Me', 'Dominic Cooper & Amanda Seyfried', 'mamma-mia-2008', [], 'Sky and Sophie sing on the beach.'],
  ['Jai Ho', 'A.R. Rahman', 'slumdog-millionaire-2008', [], 'The railway station dance during the end credits.'],
  ['Paper Planes', 'M.I.A.', 'slumdog-millionaire-2008', [], 'Jamal and Salim ride trains across India.', { trackId: 296393515 }],
  ['Supermassive Black Hole', 'Muse', 'twilight-2008', [], 'The Cullens\' thunderstorm baseball game.'],
  ['Flightless Bird, American Mouth', 'Iron & Wine', 'twilight-2008', [], 'Bella and Edward dance at the prom.'],
  ['Back in Black', 'AC/DC', 'iron-man-2008', [], 'Opens the film as Tony rides in the Humvee in Afghanistan.'],
  ['Who Let the Dogs Out', 'Baha Men', 'the-hangover-2009', [], 'Heard in the film.'],
  ['You Make My Dreams', 'Daryl Hall & John Oates', '500-days-of-summer-2009', [], 'Tom\'s morning-after dance number in the park.'],
  ['There Is a Light That Never Goes Out', 'The Smiths', '500-days-of-summer-2009', [], 'Summer recognizes Tom\'s headphones in the elevator.'],
  ['Sweet Disposition', 'The Temper Trap', '500-days-of-summer-2009', [], 'Tom and Summer\'s happiest stretch.'],
  ['For Whom the Bell Tolls', 'Metallica', 'zombieland-2009', [], 'Opens the film over slow-motion zombie chaos.'],
  ['The Times They Are A-Changin\'', 'Bob Dylan', 'watchmen-2009', [], 'The opening-credits history of costumed heroes.'],
  ['Cat People (Putting Out Fire)', 'David Bowie', 'inglourious-basterds-2009', [], 'Shosanna prepares for the premiere night.'],

  // 2010s
  ['Pocketful of Sunshine', 'Natasha Bedingfield', 'easy-a-2010', [], 'Olive sings it repeatedly over a weekend.'],
  ['Nightcall', 'Kavinsky', 'drive-2011', [], 'The opening-credits drive through Los Angeles.'],
  ['A Real Hero', 'College & Electric Youth', 'drive-2011', [], 'The Driver takes Irene and her son to the river.'],
  ['Hold On', 'Wilson Phillips', 'bridesmaids-2011', [], 'Wilson Phillips performs it at the wedding.'],
  ['Heroes', 'David Bowie', 'perks-of-being-a-wallflower-2012', [], 'Sam stands up in the truck bed in the tunnel.'],
  ['Cups (When I\'m Gone)', 'Anna Kendrick', 'pitch-perfect-2012', [], 'Beca\'s cup-rhythm audition.', { term: 'Cups Pitch Perfect Anna Kendrick' }],
  ['Skyfall', 'Adele', 'skyfall-2012', [], 'The film\'s title song over the opening titles.'],
  ['Let It Go', 'Idina Menzel', 'frozen-2013', [], 'Elsa builds her ice palace.'],
  ['Do You Want to Build a Snowman?', 'Kristen Bell, Agatha Lee Monn & Katie Lopez', 'frozen-2013', [], 'Anna knocks on Elsa\'s door over the years.'],
  ['Happy', 'Pharrell Williams', 'despicable-me-2-2013', [], 'Gru is overjoyed after his first date.'],
  ['Come and Get Your Love', 'Redbone', 'guardians-of-the-galaxy-2014', [], 'Quill dances through the ruins of Morag in the opening.'],
  ['I Want You Back', 'The Jackson 5', 'guardians-of-the-galaxy-2014', [], 'Baby Groot dances in the final scene.'],
  ['Everything Is Awesome', 'Tegan and Sara feat. The Lonely Island', 'lego-movie-2014', [], 'Emmet\'s favorite song during his morning routine.'],
  ['See You Again', 'Wiz Khalifa feat. Charlie Puth', 'furious-7-2015', [], 'The final drive tribute to Paul Walker.'],
  ['Writing\'s on the Wall', 'Sam Smith', 'spectre-2015', [], 'The film\'s theme song over the opening titles.'],
  ['Love Me Like You Do', 'Ellie Goulding', 'fifty-shades-of-grey-2015', [], 'Christian takes Anastasia on a glider flight.'],
  ['Angel of the Morning', 'Juice Newton', 'deadpool-2016', [], 'The freeze-frame opening credits on the highway.'],
  ['How Far I\'ll Go', 'Auli\'i Cravalho', 'moana-2016', [], 'Moana longs to sail beyond the reef.'],
  ['You\'re Welcome', 'Dwayne Johnson', 'moana-2016', [], 'Maui boasts about his deeds.'],
  ['Can\'t Stop the Feeling!', 'Justin Timberlake', 'trolls-2016', [], 'The trolls\' party finale.'],
  ['City of Stars', 'Ryan Gosling & Emma Stone', 'la-la-land-2016', [], 'Sebastian sings on the pier, later a duet at the piano.'],
  ['Another Day of Sun', 'La La Land Cast', 'la-la-land-2016', [], 'The freeway traffic-jam opening number.'],
  ['Bellbottoms', 'The Jon Spencer Blues Explosion', 'baby-driver-2017', [], 'The opening bank-robbery getaway.'],
  ['Harlem Shuffle', 'Bob & Earl', 'baby-driver-2017', [], 'Baby\'s coffee run, timed to the beat.'],
  ['Brighton Rock', 'Queen', 'baby-driver-2017', [], 'The climactic parking-garage showdown.'],
  ['Debora', 'T. Rex', 'baby-driver-2017', [], 'Baby and Debora talk about songs with their names.'],
  ['Mr. Blue Sky', 'Electric Light Orchestra', 'guardians-of-the-galaxy-vol-2-2017', [], 'Baby Groot dances during the opening battle.'],
  ['The Chain', 'Fleetwood Mac', 'guardians-of-the-galaxy-vol-2-2017', [], 'The Guardians regroup; used twice in the film.'],
  ['Brandy (You\'re a Fine Girl)', 'Looking Glass', 'guardians-of-the-galaxy-vol-2-2017', [], 'Ego explains the song\'s meaning to Quill.'],
  ['Immigrant Song', 'Led Zeppelin', 'thor-ragnarok-2017', [], 'Thor fights Surtur\'s minions and storms the Bifrost.'],
  ['This Is Me', 'Keala Settle', 'greatest-showman-2017', [], 'Lettie leads the performers after being shut out of a party.'],
  ['Rewrite the Stars', 'Zac Efron & Zendaya', 'greatest-showman-2017', [], 'Phillip and Anne\'s trapeze duet.'],
  ['Un Poco Loco', 'Anthony Gonzalez & Gael García Bernal', 'coco-2017', [], 'Miguel and Hector perform at the talent show.'],
  ['All the Stars', 'Kendrick Lamar & SZA', 'black-panther-2018', [], 'Written for the film; plays at the end.'],
  ['Shallow', 'Lady Gaga & Bradley Cooper', 'a-star-is-born-2018', [], 'Ally joins Jack on stage for the first time.'],
  ['Always Remember Us This Way', 'Lady Gaga', 'a-star-is-born-2018', [], 'Ally performs it on stage.'],
  ['Sunflower', 'Post Malone & Swae Lee', 'spider-man-into-the-spider-verse-2018', [], 'Miles sings along in his headphones while drawing.', { term: 'Sunflower Spider-Man Into the Spider-Verse Post Malone' }],
  ['What\'s Up Danger', 'Blackway & Black Caviar', 'spider-man-into-the-spider-verse-2018', [], 'Miles takes his leap of faith off the skyscraper.'],
  ['Just a Girl', 'No Doubt', 'captain-marvel-2019', [], 'Carol fights her way through the Skrull ship.'],
  ['That\'s Life', 'Frank Sinatra', 'joker-2019', [], 'Plays at the end of the film.'],

  // 2020s
  ['We Don\'t Talk About Bruno', 'Carolina Gaitán, Mauro Castillo, Adassa, Rhenzy Feliz, Diane Guerrero & Stephanie Beatriz', 'encanto-2021', [], 'The family tells Mirabel about their estranged uncle.', { term: 'We Don\'t Talk About Bruno Encanto' }],
  ['Surface Pressure', 'Jessica Darrow', 'encanto-2021', [], 'Luisa admits the strain of being the strong one.'],
  ['Hold My Hand', 'Lady Gaga', 'top-gun-maverick-2022', [], 'Written for the film; plays at the end.'],
  ['Dance the Night', 'Dua Lipa', 'barbie-2023', [], 'The Barbieland dance party.'],
  ['I\'m Just Ken', 'Ryan Gosling', 'barbie-2023', [], 'Ken\'s big musical number during the beach battle.'],
  ['What Was I Made For?', 'Billie Eilish', 'barbie-2023', [], 'Barbie\'s reflective montage.'],
  ['Murder on the Dancefloor', 'Sophie Ellis-Bextor', 'saltburn-2023', [], 'The final dance through the estate.'],
  ['Bye Bye Bye', '*NSYNC', 'deadpool-and-wolverine-2024', [], 'Deadpool\'s opening-credits fight dance.', { term: 'Bye Bye Bye NSYNC' }],
  ['Popular', 'Ariana Grande', 'wicked-2024', ['zombieland-2009'], 'Glinda offers Elphaba a makeover.'],
  ['Defying Gravity', 'Cynthia Erivo & Ariana Grande', 'wicked-2024', [], 'Elphaba takes flight in the finale.'],
  ['Ain\'t No Love in Oklahoma', 'Luke Combs', 'twisters-2024', [], 'Written for the film; plays as the storm chasers hit the road.'],
  ['I Lied to You', 'Miles Caton', 'sinners-2025', [], 'Sammie performs at the juke joint on opening night.'],
  ['Golden', 'HUNTR/X', 'kpop-demon-hunters-2025', [], 'The group performs it as they work to seal the demon barrier.', { term: 'Golden HUNTR/X KPop Demon Hunters' }],
];
